### ISSUE TITLE
Suggestions for time of submission

### ISSUE THREAD

**Issue by eteq** [jwuphysics/xSAGA#1]
First some suggestions for improving the presentation of the README
* " we use a proprietary redshift catalog" -> "we use a larger redshift catalog"
* Put "results" before "data"
* Put the first pararaph of "results" as the last paragraph of "data"
* Make the Bold text in "Results" bolder - maybe even make it a section heading
* "Our findings agree with the SAGA Survey's results." -> "xSAGA confirms and extends key SAGA Survey results."

* *maybe* add a `gh-pages` branch that is a basic HTML that is just a rendering of this README (with a "click here to go to the github repo" button)? Then you can point people to the web site directly and they'll see the results first instead of the github cruft.

Now some code-layout ideas:
* Rename `requirements.txt` to `requirements_at_publication.txt`, and then make a `requirements.txt` file that is just the minimal requirements *without* specific versions.  Then in the `README` tell interested folks to use that, since they can do that without mucking up an existing environment. (You might then need to add a clarification "if you want to be sure the figures are exactly the same as the paper use `requirements_at_publication.txt` in a dedicated environment" or something like that.
* You could consider adding a `Dockerfile` to make it easy for people to spin up a container that can run the notebooks.  If you want to see my take on you to do this check out https://github.com/eteq/astrocontainer (feel free to use that as-is if it's useful).

**Comment by jwuphysics** [comment]
Thanks for the suggestions. These sound great!

I'm implementing a simple `requirements.txt` without version numbers or most of the dependencies. Might be able to generate one directly using [`pip-chill`](https://github.com/rbanffy/pip-chill) although I'm not sure how well that plays with Pytorch + CUDA requirements.
